### ISSUE TITLE
Error from the start

### ISSUE THREAD

**Issue by david-sledge** [jonascarpay/jonascarpay.github.io#2]
Under "Using template-haskell" the last paragraph reads: "From here, enter the shell and you should have all tools available to you." Unfortunately, entering the shell at this point gave me

    "error: getting status of '/home/<path>/<to>/<project>/default.nix': No such file or directory"

**Comment by jonascarpay** [comment]
Did you add/stage everything in git? That's usually the issue with these kinds of errors.

**Comment by david-sledge** [comment]
Yes, everything's staged. The [template-haskell](https://github.com/jonascarpay/template-haskell) repo doesn't have a `default.nix`. Was `wizard.sh` supposed to create it?

**Comment by jonascarpay** [comment]
Oh, you're using the non-flake commands. That's addressed [here](https://github.com/jonascarpay/template-haskell/tree/2ca38e6eebb776bedfc758cf04735d60676c24a1#flakes) in the README.

Note that the original blog post has been deprecated since you opened the original post. Nix has improved, and you now get better ergonomics with the "regular" Nix. The README on the master branch should help you on your way. Sorry for the confusion.
